-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 18, 2024 at 01:22 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `car_database`
--

-- --------------------------------------------------------

--
-- Table structure for table `cars`
--

CREATE TABLE `cars` (
  `id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `price` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `speed` varchar(255) DEFAULT NULL,
  `engine_type` varchar(255) DEFAULT NULL,
  `build` varchar(255) DEFAULT NULL,
  `weight` varchar(255) DEFAULT NULL,
  `material` varchar(255) DEFAULT NULL,
  `engine_l` varchar(255) DEFAULT NULL,
  `hp` varchar(255) DEFAULT NULL,
  `history` text DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `cars`
--

INSERT INTO `cars` (`id`, `name`, `price`, `description`, `speed`, `engine_type`, `build`, `weight`, `material`, `engine_l`, `hp`, `history`, `image_url`) VALUES
(61, 'Ferrari SF90 Stradale', '$846,888 AUD', 'The Ferrari SF90 Stradale is a hybrid supercar that combines stunning performance with cutting-edge technology. It is one of the most powerful and advanced models ever produced by Ferrari.', '2.5s', 'V8 Hybrid', 'Coupe', '1.57 tonnes', 'Carbon Fiber', '4.0L', '986hp', 'The Ferrari SF90 Stradale was introduced in 2019 as Ferrari’s first series-production plug-in hybrid electric vehicle (PHEV). Named in honor of Ferrari’s 90th anniversary, the SF90 Stradale is a testament to the brand’s commitment to innovation and performance. The car features a 4.0-liter V8 engine paired with three electric motors, producing a combined output of 986 horsepower. This allows the SF90 Stradale to achieve unprecedented levels of performance, with a top speed of 340 km/h and a 0-100 km/h time of just 2.5 seconds. The SF90 Stradale represents a new chapter in Ferrari’s history, blending traditional combustion engine power with electric propulsion to create a hypercar for the modern era.', 'images/ferrari/sf90_stradale.jpg'),
(62, 'Ferrari SF90 Spider', '$960,888 AUD', 'The Ferrari SF90 Spider is the convertible version of the SF90 Stradale, offering the same incredible performance and hybrid technology with the added thrill of open-top driving.', '2.5s', 'V8 Twin Turbo', 'Convertible', '1.67 tonnes', 'Carbon Fiber', '4.0L', '986hp', 'Unveiled in 2020, the Ferrari SF90 Spider builds on the success of the SF90 Stradale by offering an open-top experience. It features the same 4.0-liter V8 engine and three electric motors as the Stradale, delivering a total of 986 horsepower. The retractable hardtop can be opened in just 14 seconds, allowing drivers to enjoy the exhilaration of the SF90’s performance with the wind in their hair. The SF90 Spider is a marvel of engineering, combining the latest in hybrid technology with Ferrari’s iconic design and craftsmanship. It represents a new level of versatility in the world of supercars, allowing for both track-focused performance and luxurious cruising.', 'images/ferrari/sf90_spider.jpg'),
(63, 'Ferrari 296 GTB', '$568,888 AUD', 'The Ferrari 296 GTB is a plug-in hybrid sports car that represents a new era of performance and efficiency for Ferrari. It features a compact V6 engine paired with an electric motor.', '2.9s', 'Twin Turbo V6 Hybrid', 'Coupe', '1.47 tonnes', 'Aluminum', '3.0L', '818hp', 'Introduced in 2021, the Ferrari 296 GTB marks the return of the V6 engine to Ferrari’s lineup, but with a modern twist. The 296 GTB features a 3.0-liter twin-turbo V6 engine combined with an electric motor, producing a total of 818 horsepower. This setup allows the car to accelerate from 0-100 km/h in just 2.9 seconds. The 296 GTB is designed to deliver both performance and efficiency, with the ability to run on electric power alone for short distances. Its compact size and advanced aerodynamics make it a nimble and capable sports car, while the hybrid powertrain offers a glimpse into the future of Ferrari performance vehicles.', 'images/ferrari/296_gtb.jpg'),
(64, 'Ferrari 296 GTS', '$618,888 AUD', 'The Ferrari 296 GTS is the convertible variant of the 296 GTB, offering the same hybrid powertrain and performance with the added excitement of open-top driving.', '2.9s', 'V6 Hybrid', 'Convertible', '1.54 tonnes', 'Aluminum', '3.0L', '818hp', 'Launched in 2022, the Ferrari 296 GTS brings the thrill of the 296 GTB’s hybrid performance to a convertible format. It shares the same 3.0-liter V6 engine and electric motor setup, producing 818 horsepower. The retractable hardtop can be opened or closed in 14 seconds, even at speeds of up to 45 km/h. The 296 GTS combines Ferrari’s latest hybrid technology with the joy of open-air driving, making it a versatile and exciting addition to the Ferrari lineup. The GTS offers a unique driving experience, blending cutting-edge engineering with the timeless appeal of a Ferrari convertible.', 'images/ferrari/296_gts.jpg'),
(65, 'Ferrari 12Cilindri', '$689,888 AUD', 'The Ferrari 12Cilindri is a powerful grand tourer that combines luxury and performance in a stylish package. It is equipped with a V12 engine, delivering impressive power and a thrilling driving experience.', '3.4s', 'V12', 'Coupe', '1.75 tonnes', 'Aluminum', '6.5L', '789hp', 'The Ferrari 12Cilindri represents the epitome of grand touring performance. With its V12 engine and elegant design, it offers a perfect blend of power, luxury, and style. The 12Cilindri is built for long-distance driving, with a spacious and comfortable interior that ensures a relaxing journey. At the same time, its powerful engine delivers the exhilarating performance that Ferrari is known for. This model continues Ferrari’s tradition of building V12-powered grand tourers, combining modern technology with classic Ferrari craftsmanship.', 'images/ferrari/12cilindri.jpg'),
(66, 'Ferrari 12Cilindri Spider', '$739,888 AUD', 'The Ferrari 12Cilindri Spider is the open-top version of the 12Cilindri grand tourer, offering the same luxurious performance with the added thrill of open-air driving.', '3.4s', 'V12', 'Convertible', '1.77 tonnes', 'Aluminum', '6.5L', '789hp', 'The Ferrari 12Cilindri Spider takes the grand touring experience to the next level with its retractable hardtop roof. This model combines the power and luxury of the 12Cilindri with the freedom and excitement of open-top driving. The Spider version maintains the same V12 engine and performance characteristics, ensuring that drivers can enjoy the best of both worlds. Whether cruising along the coast or tackling a mountain road, the 12Cilindri Spider delivers an unforgettable driving experience, combining Ferrari’s iconic V12 power with the joy of open-air motoring.', 'images/ferrari/12cilindri_spider.jpg'),
(67, 'Ferrari Purosangue', '$808,888 AUD', 'The Ferrari Purosangue is Ferrari\'s first-ever SUV, blending the brand\'s legendary performance with the practicality and versatility of a luxury SUV.', '3.3s', 'V12', 'SUV', '2.18 tonnes', 'Aluminum', '6.5L', '715hp', 'The Ferrari Purosangue, meaning \"Thoroughbred\" in Italian, represents Ferrari\'s entry into the luxury SUV market. Launched in 2023, the Purosangue is designed to combine the performance and handling of a Ferrari sports car with the comfort and practicality of an SUV. Powered by a naturally aspirated 6.5-liter V12 engine, the Purosangue delivers 715 horsepower, making it one of the most powerful SUVs on the market. The Purosangue features all-wheel drive, adaptive suspension, and a luxurious interior with seating for four. It is built to provide a unique driving experience, blending Ferrari\'s racing heritage with the demands of modern-day motoring. The Purosangue is a bold step for Ferrari, expanding its lineup into a new and growing market segment.', 'images/ferrari/purosangue.jpg'),
(68, 'Ferrari Roma', '$409,888 AUD', 'The Ferrari Roma is a stylish grand tourer that combines elegant design with thrilling performance. It is a modern interpretation of Ferrari\'s classic front-engine GT cars.', '3.4s', 'V8 Turbo', 'Coupe', '1.57 tonnes', 'Aluminum', '3.9L', '612hp', 'Introduced in 2020, the Ferrari Roma represents a new chapter in Ferrari\'s long history of front-engine grand tourers. The Roma features a 3.9-liter twin-turbo V8 engine that produces 612 horsepower, allowing it to accelerate from 0-100 km/h in just 3.4 seconds. The Roma\'s design is inspired by the classic Ferrari GT cars of the 1950s and 1960s, with a sleek, minimalist look that emphasizes elegance and sophistication. Inside, the Roma offers a luxurious and modern interior, with advanced technology and high-quality materials. The Roma is designed to be a versatile grand tourer, capable of delivering both comfort and performance on long journeys.', 'images/ferrari/roma.jpg'),
(69, 'Ferrari Roma Spider', '$459,888 AUD', 'The Ferrari Roma Spider is the convertible version of the Roma grand tourer, offering the same elegant design and performance with the added thrill of open-top driving.', '3.4s', 'V8 Twin Turbo', 'Convertible', '1.6 tonnes', 'Aluminum', '3.9L', '612hp', 'The Ferrari Roma Spider, introduced in 2021, brings the elegance and performance of the Roma to an open-top format. Like the coupe, the Roma Spider is powered by a 3.9-liter twin-turbo V8 engine that produces 612 horsepower. The convertible roof can be opened or closed in just 14 seconds, even at speeds of up to 50 km/h. The Roma Spider offers the same luxurious interior and advanced technology as the coupe, with the added joy of open-air driving. It is designed for those who want to enjoy Ferrari\'s grand touring experience with the wind in their hair.', 'images/ferrari/roma_spider.jpg'),
(70, 'Ferrari SF90 XX Stradale', '$1,045,888 AUD', 'The Ferrari SF90 XX Stradale is a track-focused version of the SF90 Stradale, offering even greater performance and exclusivity.', '2.3s', 'V8 Twin Turbo', 'Coupe', '1.54 tonnes', 'Carbon Fiber', '4.0L', '986hp', 'The Ferrari SF90 XX Stradale, introduced in 2023, is the ultimate expression of the SF90 platform. This limited-edition model is designed for track enthusiasts, with a focus on performance and handling. It features the same hybrid powertrain as the SF90 Stradale, but with various upgrades to the chassis, aerodynamics, and suspension. The SF90 XX Stradale is lighter and more focused than the standard SF90, with increased downforce and more aggressive styling. This model is intended for those who want the most extreme version of Ferrari\'s hybrid supercar, with a driving experience that is closer to that of a race car.', 'images/ferrari/sf90_xx_stradale.jpg'),
(71, 'Ferrari SF90 XX Spider', '$1,175,888 AUD', 'The Ferrari SF90 XX Spider is the convertible version of the SF90 XX Stradale, offering the same track-focused performance with the added thrill of open-top driving.', '2.3s', 'V8 Hybrid', 'Convertible', '1.57 tonnes', 'Carbon Fiber', '4.0L', '986hp', 'The Ferrari SF90 XX Spider takes the extreme performance of the SF90 XX Stradale and adds the exhilaration of open-air driving. This limited-edition model features the same hybrid powertrain and performance upgrades as the Stradale, but with a retractable hardtop that allows drivers to enjoy the experience with the roof down. The SF90 XX Spider is designed for those who want the ultimate Ferrari driving experience, combining track-level performance with the freedom of open-top motoring. This model represents the pinnacle of Ferrari\'s hybrid technology and engineering, offering an unparalleled driving experience.', 'images/ferrari/sf90_xx_spider.jpg'),
(83, 'Ferrari 812 Competizione', '$818,888 AUD', 'The Ferrari 812 Competizione is a limited-edition, track-focused variant of the 812 Superfast. It delivers extreme performance and features several enhancements for improved aerodynamics and handling.', '2.8s', 'V12', 'Coupe', '1.63 tonnes', 'Aluminum', '6.5L', '819hp', 'Launched in 2021, the Ferrari 812 Competizione represents the pinnacle of Ferrari’s front-engine V12 technology. This model is a hardcore, track-oriented version of the 812 Superfast, designed for maximum performance and driver engagement. The 812 Competizione is powered by a naturally aspirated 6.5-liter V12 engine that produces 819 horsepower, making it one of the most powerful V12s Ferrari has ever produced. The car features extensive aerodynamic modifications, including a redesigned front fascia, rear diffuser, and innovative “aero bridge” elements that enhance downforce and stability. The 812 Competizione also benefits from Ferrari’s advanced electronic systems, including rear-wheel steering and Side Slip Control, which improve handling and agility on the track. This model is a celebration of Ferrari’s V12 heritage and a testament to the brand’s commitment to pushing the boundaries of performance.', 'images/ferrari/812_competizione.jpg'),
(84, 'Ferrari 812 Competizione A', '$889,888 AUD', 'The Ferrari 812 Competizione A is the open-top version of the 812 Competizione, offering the same extreme performance with the added thrill of open-air driving.', '2.8s', 'V12', 'Convertible', '1.64 tonnes', 'Aluminum', '6.5L', '819hp', 'Unveiled alongside the 812 Competizione in 2021, the Ferrari 812 Competizione A (Aperta) is the convertible variant of this high-performance model. Like the coupe, the 812 Competizione A is powered by a 6.5-liter V12 engine producing 819 horsepower. The retractable roof allows drivers to experience the full symphony of the V12 engine while enjoying the open air. Despite the open-top design, the 812 Competizione A retains the same aerodynamic enhancements and advanced electronic systems as the coupe, ensuring that it delivers the same level of performance and handling. This model is a limited edition, aimed at collectors and enthusiasts who want the ultimate Ferrari V12 experience with the freedom of open-top motoring.', 'images/ferrari/812_competizione_a.jpg'),
(85, 'Ferrari Daytona SP3', '$3,150,000 AUD', 'The Ferrari Daytona SP3 is a part of Ferrari’s Icona series, inspired by the classic sports prototypes from the 1960s. It combines retro styling with modern engineering to create a unique and powerful supercar.', '2.85s', 'V12', 'Coupe', '1.48 tonnes', 'Carbon Fiber', '6.5L', '828hp', 'The Ferrari Daytona SP3, introduced in 2021, is the latest model in Ferrari’s Icona series, which pays homage to the brand’s legendary sports prototypes from the 1960s. The Daytona SP3 is inspired by the iconic Ferrari 330 P4 and 412 P, featuring a striking design that combines retro elements with cutting-edge technology. The car is powered by a 6.5-liter V12 engine that produces 828 horsepower, making it the most powerful naturally aspirated V12 in Ferrari’s history. The Daytona SP3’s body is made entirely of carbon fiber, contributing to its lightweight construction and exceptional performance. The car’s aerodynamics are optimized for maximum downforce and stability, with features such as a large rear diffuser and active aerodynamics. The Daytona SP3 is a celebration of Ferrari’s racing heritage, offering a unique blend of past and present in a limited-edition package.', 'images/ferrari/daytona_sp3.jpg'),
(86, 'Ferrari Monza SP1', '$2,880,000 AUD', 'The Ferrari Monza SP1 is a limited-edition, single-seater speedster that combines modern technology with classic Ferrari styling. It is part of the Icona series and is designed for the ultimate driving experience.', '2.9s', 'V12', 'Speedster', '1.5 tonnes', 'Carbon Fiber', '6.5L', '809hp', 'The Ferrari Monza SP1, introduced in 2018, is one of the first models in Ferrari’s Icona series, which takes inspiration from the brand’s iconic cars of the past. The SP1 is a single-seater speedster that pays homage to the Ferrari barchettas of the 1950s. It features a sleek, minimalist design with no roof or windshield, emphasizing the pure driving experience. The car is powered by a 6.5-liter V12 engine that produces 809 horsepower, making it one of the most powerful Ferrari road cars ever built. The Monza SP1’s lightweight carbon fiber construction and advanced aerodynamics allow it to deliver exceptional performance, with a 0-100 km/h time of just 2.9 seconds. This model is designed for Ferrari’s most dedicated enthusiasts, offering a unique blend of nostalgia and cutting-edge technology.', 'images/ferrari/monza_sp1.jpg'),
(87, 'Ferrari Monza SP2', '$2,880,000 AUD', 'The Ferrari Monza SP2 is the two-seater variant of the Monza SP1, offering the same thrilling performance and design with the added ability to share the experience with a passenger.', '2.9s', 'V12', 'Speedster', '1.5 tonnes', 'Carbon Fiber', '6.5L', '809hp', 'The Ferrari Monza SP2, introduced alongside the SP1 in 2018, is the two-seater version of this iconic speedster. Like the SP1, the SP2 is part of Ferrari’s Icona series, which celebrates the brand’s rich history by reinterpreting classic designs with modern technology. The SP2 retains the same 6.5-liter V12 engine and performance characteristics as the SP1, delivering 809 horsepower and a 0-100 km/h time of 2.9 seconds. The key difference is the addition of a second seat, allowing drivers to share the exhilarating experience with a passenger. The Monza SP2 combines Ferrari’s legendary performance with a design that is both timeless and cutting-edge, making it a true collector’s item.', 'images/ferrari/monza_sp2.jpg'),
(88, 'Ferrari LaFerrari Aperta', '$6,250,000 AUD', 'The Ferrari LaFerrari Aperta is the open-top version of the LaFerrari, combining the same hybrid powertrain and extreme performance with the added thrill of open-air driving.', '2.6s', 'V12 Hybrid', 'Convertible', '1.59 tonnes', 'Carbon Fiber', '6.3L', '950hp', 'The Ferrari LaFerrari Aperta was unveiled in 2016 as the convertible version of the LaFerrari, Ferrari’s flagship hypercar. The Aperta retains the same hybrid powertrain as the coupe, featuring a 6.3-liter V12 engine combined with an electric motor to produce a total of 950 horsepower. The car’s advanced hybrid technology allows it to deliver astonishing performance, with a top speed of over 350 km/h and a 0-100 km/h time of just 2.6 seconds. The LaFerrari Aperta features a removable carbon fiber roof panel, allowing drivers to enjoy the car’s performance with the wind in their hair. This model is a celebration of Ferrari’s 70th anniversary, and it was produced in extremely limited numbers, making it one of the most exclusive Ferrari models ever built.', 'images/ferrari/laferrari_aperta.jpg'),
(89, 'Ferrari LaFerrari', '$4,850,000 AUD', 'The Ferrari LaFerrari is a hybrid hypercar that represents the pinnacle of Ferrari’s engineering and design. It combines a V12 engine with an electric motor for extreme performance and efficiency.', '2.6s', 'V12 Hybrid', 'Coupe', '1.58 tonnes', 'Carbon Fiber', '6.3L', '950hp', 'The Ferrari LaFerrari, introduced in 2013, is Ferrari’s first hybrid hypercar and the most powerful road car ever produced by the brand at the time. The LaFerrari is powered by a 6.3-liter V12 engine paired with an electric motor, producing a combined output of 950 horsepower. This hybrid powertrain allows the LaFerrari to achieve a top speed of over 350 km/h and a 0-100 km/h time of just 2.6 seconds. The car’s design is a perfect blend of form and function, with a focus on aerodynamics and lightweight construction. The LaFerrari features active aerodynamics and advanced electronics, making it one of the most technologically advanced cars ever built by Ferrari. This model is a symbol of Ferrari’s commitment to pushing the boundaries of performance and innovation, and it remains a benchmark in the world of hypercars.', 'images/ferrari/laferrari.jpg'),
(90, 'Ferrari Enzo Ferrari', '$3,000,000 AUD', 'The Ferrari Enzo Ferrari is a legendary supercar that was built to commemorate the company’s founder, Enzo Ferrari. It features a powerful V12 engine and advanced technology derived from Formula 1.', '3.3s', 'V12', 'Coupe', '1.48 tonnes', 'Carbon Fiber', '6.0L', '651hp', 'The Ferrari Enzo Ferrari, named after the company’s founder, was introduced in 2002 as a tribute to the brand’s heritage and racing success. The Enzo is powered by a 6.0-liter V12 engine that produces 651 horsepower, allowing it to reach a top speed of 350 km/h and accelerate from 0 to 100 km/h in just 3.3 seconds. The car features advanced technology derived from Ferrari’s Formula 1 program, including carbon fiber construction, active aerodynamics, and an automated manual transmission. The Enzo’s design is focused on performance and efficiency, with a minimalist interior and a focus on driver engagement. Only 400 units were produced, making the Enzo one of the most exclusive and sought-after Ferrari models ever built. The Enzo remains a symbol of Ferrari’s dedication to engineering excellence and its commitment to producing the world’s finest supercars.', 'images/ferrari/enzo_ferrari.jpg'),
(91, 'Ferrari F40', '$4,400,000 AUD', 'The Ferrari F40 is one of the most iconic supercars ever built. It was the last car personally approved by Enzo Ferrari and was designed to celebrate Ferrari’s 40th anniversary.', '3.8s', 'V8', 'Coupe', '1.1 tonnes', 'Carbon Fiber', '2.9L', '471hp', 'The Ferrari F40, introduced in 1987, is widely regarded as one of the greatest supercars of all time. It was the last car to be personally approved by Enzo Ferrari before his passing, and it was built to celebrate Ferrari’s 40th anniversary. The F40 is powered by a twin-turbocharged 2.9-liter V8 engine that produces 471 horsepower, allowing it to reach a top speed of 324 km/h and accelerate from 0 to 100 km/h in 3.8 seconds. The car’s design is focused on performance and weight reduction, with extensive use of carbon fiber, Kevlar, and aluminum in its construction. The F40 features a minimalist interior with no electronic aids, emphasizing the pure driving experience. Only 1,315 units were produced, making the F40 a highly sought-after collector’s item. The F40’s combination of raw power, lightweight construction, and timeless design has cemented its status as a true automotive legend.', 'images/ferrari/f40.jpg'),
(92, 'Ferrari F50', '$4,500,000 AUD', 'The Ferrari F50 is a limited-edition supercar that was built to celebrate Ferrari’s 50th anniversary. It features a Formula 1-derived V12 engine and a carbon fiber chassis.', '3.7s', 'V12', 'Convertible', '1.23 tonnes', 'Carbon Fiber', '4.7L', '513hp', 'The Ferrari F50 was introduced in 1995 to mark Ferrari’s 50th anniversary. It was designed to be as close as possible to a road-going Formula 1 car, with a naturally aspirated 4.7-liter V12 engine derived from Ferrari’s 1990 Formula 1 car. The engine produces 513 horsepower, enabling the F50 to accelerate from 0 to 100 km/h in 3.7 seconds and reach a top speed of 325 km/h. The car’s chassis is made entirely of carbon fiber, and it features a removable hardtop that allows it to be driven as a convertible. The F50’s design is focused on performance and driver engagement, with a minimalist interior and no electronic driving aids. Only 349 units were produced, making the F50 one of the rarest and most desirable Ferrari models. The F50 is celebrated for its raw, uncompromising performance and its direct connection to Ferrari’s racing heritage.', 'images/ferrari/f50.jpg'),
(93, 'Ferrari GTO', '$1,800,000 AUD', 'The Ferrari GTO is a high-performance version of the 599 GTB Fiorano. It features a powerful V12 engine and numerous upgrades for improved performance and handling.', '3.35s', 'V12', 'Coupe', '1.68 tonnes', 'Aluminum', '6.0L', '670hp', 'The Ferrari 599 GTO, introduced in 2010, is a high-performance version of the 599 GTB Fiorano. The GTO designation stands for “Gran Turismo Omologata,” a name that has been used on only two previous Ferrari models: the 250 GTO and the 288 GTO. The 599 GTO is powered by a 6.0-liter V12 engine that produces 670 horsepower, making it the most powerful road-going Ferrari at the time of its release. The car features numerous upgrades over the standard 599 GTB, including a lighter chassis, revised suspension, and enhanced aerodynamics. The GTO’s performance is further improved by advanced electronic systems such as Ferrari’s F1-Trac traction control and a fast-shifting F1 gearbox. The 599 GTO can accelerate from 0 to 100 km/h in just 3.35 seconds and has a top speed of over 335 km/h. This model is a tribute to Ferrari’s racing heritage, combining the performance of a race car with the usability of a road car.', 'images/ferrari/gto.jpg'),
(94, 'Ferrari 296 GT3', '$900,000 AUD', 'The Ferrari 296 GT3 is a racing version of the 296 GTB, designed for GT3 competitions. It features extensive modifications for track use, including a lightweight body and a race-tuned hybrid powertrain.', '2.8s', 'V6 Twin Turbo Hybrid', 'Coupe', '1.3 tonnes', 'Carbon Fiber', '2.9L', '850hp', 'The Ferrari 296 GT3, introduced in 2022, is a racing version of the 296 GTB, designed specifically for GT3 class competitions. The car is powered by a race-tuned version of the 2.9-liter V6 hybrid powertrain found in the road-going 296 GTB, producing 850 horsepower. The 296 GT3 features extensive modifications for track use, including a lightweight carbon fiber body, advanced aerodynamics, and a stripped-down interior. The car’s suspension and brakes have been upgraded for racing, and it features a roll cage and other safety equipment required for GT3 racing. The 296 GT3 is a continuation of Ferrari’s long history of success in GT racing, offering teams and drivers a highly competitive and technologically advanced platform for racing at the highest levels.', 'images/ferrari/296_gt3.jpg'),
(95, '1947 Ferrari 125 S', '$12,000,000 AUD', 'The Ferrari 125 S is the first car to bear the Ferrari name. It is powered by a V12 engine designed by Gioachino Colombo and represents the beginning of Ferrari’s legacy.', '12s', 'V12', 'Sports Car', '0.65 tonnes', 'Steel', '1.5L', '118hp', 'The Ferrari 125 S, introduced in 1947, holds the distinction of being the first car to bear the Ferrari name. The 125 S was designed by Gioachino Colombo and featured a 1.5-liter V12 engine, which became the foundation of Ferrari’s reputation for building powerful and high-revving engines. The 125 S was built in two examples, both of which were used in competition. The car made its debut at the Piacenza Circuit, where it showed great potential but did not finish due to a mechanical issue. However, just two weeks later, the 125 S won the Grand Prix of Rome, marking the first of many victories for Ferrari. The 125 S’s success on the track helped establish Ferrari as a serious contender in the world of motorsports. The car’s combination of innovative engineering and competitive spirit laid the groundwork for Ferrari’s future success in both racing and road cars.', 'images/ferrari/125_s.jpg'),
(96, '1947 Ferrari 159 S', '$13,000,000 AUD', 'The Ferrari 159 S is an evolution of the 125 S, featuring an enlarged V12 engine and improved performance. It was one of the early successes that helped establish Ferrari as a dominant force in motorsport.', '11.5s', 'V12', 'Sports Car', '0.65 tonnes', 'Steel', '1.9L', '125hp', 'The Ferrari 159 S, introduced in 1947, was an evolution of the Ferrari 125 S, featuring an enlarged 1.9-liter V12 engine. The 159 S was designed to build on the success of the 125 S and further establish Ferrari’s presence in the world of motorsports. The car retained the same basic chassis and layout as the 125 S but featured a more powerful engine, which produced 125 horsepower. This increase in power allowed the 159 S to achieve better performance on the track, with a top speed of around 170 km/h. The 159 S was used in various races, including the Mille Miglia and the Targa Florio, where it demonstrated Ferrari’s growing competitiveness. The 159 S played a crucial role in Ferrari’s early history, helping to solidify the brand’s reputation for building high-performance cars and achieving success in racing.', 'images/ferrari/159_s.jpg'),
(97, '1948 Ferrari 166 Inter', '$15,000,000 AUD', 'The Ferrari 166 Inter was Ferrari’s first road car, designed for grand touring. It was powered by a 2.0-liter V12 engine and featured elegant coachwork by various Italian designers.', '10s', 'V12', 'Coupe', '0.95 tonnes', 'Steel and Aluminum', '2.0L', '110hp', 'The Ferrari 166 Inter, introduced in 1948, was Ferrari’s first road car, marking the brand’s transition from a purely racing-focused manufacturer to a builder of high-performance grand touring cars. The 166 Inter was based on the 166 Sport, a race car that had achieved success in events like the Mille Miglia and the 24 Hours of Le Mans. The 166 Inter was powered by a 2.0-liter V12 engine, producing 110 horsepower. The car was offered with a variety of elegant coachwork designs by Italian carrozzerias such as Touring, Vignale, and Ghia, reflecting the bespoke nature of early Ferrari road cars. The 166 Inter’s combination of performance, style, and exclusivity made it a desirable car for wealthy enthusiasts. The model’s success helped establish Ferrari’s reputation as a builder of luxurious and high-performance road cars, laying the foundation for the brand’s future.', 'images/ferrari/166_inter.jpg'),
(99, '1948 Ferrari 166 Inter Sport', '$16,000,000 AUD', 'The Ferrari 166 Inter Sport was an evolution of the 166 Inter, designed for both road and race use. It combined the elegance of a road car with the performance of a race car, making it versatile and highly desirable.', '9.5s', 'V12', 'Coupe', '0.93 tonnes', 'Steel and Aluminum', '2.0L', '120hp', 'The Ferrari 166 Inter Sport, introduced in 1948, was designed as a dual-purpose car, suitable for both road use and competitive racing. The model was based on the Ferrari 166 Inter, but with enhancements that made it more competitive on the track. The 166 Inter Sport featured a 2.0-liter V12 engine that produced 120 horsepower, providing a balance of power and reliability. The car was equipped with lightweight steel and aluminum bodywork, which helped to improve its performance and handling. The 166 Inter Sport was particularly successful in events like the Mille Miglia and the Targa Florio, where it demonstrated Ferrari’s ability to build cars that were both elegant and competitive. The car’s versatility and success in racing helped to solidify Ferrari’s reputation as a manufacturer of high-performance grand touring cars.', 'images/ferrari/166_inter_sport.jpg'),
(100, '1948 Ferrari 166 MM', '$17,000,000 AUD', 'The Ferrari 166 MM, also known as the “Mille Miglia,” was designed specifically for endurance racing. It became famous for winning the 1949 Mille Miglia and the 24 Hours of Le Mans, cementing Ferrari’s legacy in motorsports.', '8.5s', 'V12', 'Barchetta', '0.9 tonnes', 'Aluminum', '2.0L', '140hp', 'The Ferrari 166 MM, introduced in 1948, was a significant model in Ferrari’s early history, designed specifically for endurance racing. The “MM” stands for Mille Miglia, a famous Italian road race that the car was built to compete in. The 166 MM was powered by a 2.0-liter V12 engine, producing 140 horsepower, which allowed it to compete effectively in long-distance races. The car featured lightweight aluminum bodywork and a streamlined design that improved its performance. The 166 MM achieved significant success in motorsports, most notably winning the 1949 Mille Miglia and the 24 Hours of Le Mans, two of the most prestigious races in the world. These victories helped to establish Ferrari as a dominant force in motorsports and laid the foundation for the brand’s future success. The 166 MM is celebrated not only for its racing achievements but also for its role in defining Ferrari’s identity as a builder of high-performance, race-bred sports cars.', 'images/ferrari/166_mm.jpg'),
(102, '1950 Ferrari 195 S', '$16,000,000 AUD', 'The Ferrari 195 S was a sports version of the 195 Inter, designed for competition. It featured a more powerful engine and was used in various racing events, achieving notable success.', '9.5s', 'V12', 'Coupe', '1.05 tonnes', 'Aluminum', '2.3L', '135hp', 'The Ferrari 195 S, introduced in 1950, was the competition-oriented version of the 195 Inter, built for customers who wanted a car that could be driven both on the road and on the track. The 195 S was equipped with a 2.3-liter V12 engine, producing 135 horsepower, offering improved performance over the standard 195 Inter. The car was designed with lightweight aluminum bodywork, which helped to enhance its agility and speed. The 195 S was used in various racing events, including the Mille Miglia, where it demonstrated Ferrari’s growing competitiveness in motorsports. The car’s success on the track, combined with its elegant design, made it a popular choice among racing enthusiasts and collectors. The 195 S is a significant model in Ferrari’s history, representing the brand’s early efforts to build cars that could excel in both road and race environments.', 'images/ferrari/195_s.jpg'),
(103, '1950 Ferrari 340 America', '$17,500,000 AUD', 'The Ferrari 340 America was a powerful grand tourer designed for the American market. It featured a large V12 engine and luxurious appointments, making it a favorite among wealthy customers.', '8s', 'V12', 'Coupe', '1.2 tonnes', 'Steel', '4.1L', '220hp', 'The Ferrari 340 America, introduced in 1950, was designed as a high-performance grand touring car aimed at the American market. The car was powered by a 4.1-liter V12 engine that produced 220 horsepower, making it one of the most powerful road cars of its time. The 340 America was available with custom coachwork from some of Italy’s leading carrozzerias, including Vignale, Touring, and Ghia, which allowed customers to tailor the car’s design to their personal tastes. The car’s combination of power, luxury, and exclusivity made it highly desirable among wealthy buyers in the United States. The 340 America also had success in motorsports, competing in events such as the Mille Miglia and the Carrera Panamericana, where it demonstrated Ferrari’s engineering excellence and competitiveness. The 340 America is an important model in Ferrari’s history, representing the brand’s early efforts to establish a presence in the lucrative American market.', 'images/ferrari/340_america.jpg'),
(104, '1951 Ferrari 212 Export', '$14,500,000 AUD', 'The Ferrari 212 Export was a race-bred version of the 212 Inter, designed for competition. It featured a more powerful engine and lightweight construction, making it a formidable competitor in races.', '7.8s', 'V12', 'Coupe', '0.95 tonnes', 'Aluminum', '2.6L', '170hp', 'The Ferrari 212 Export, introduced in 1951, was the competition-oriented version of the 212 Inter, built for customers who wanted a car that could be driven both on the road and on the track. The 212 Export was powered by a 2.6-liter V12 engine that produced 170 horsepower, offering improved performance over the standard 212 Inter. The car was designed with lightweight aluminum bodywork, which helped to enhance its agility and speed. The 212 Export was used in various racing events, including the Mille Miglia, where it demonstrated Ferrari’s growing competitiveness in motorsports. The car’s success on the track, combined with its elegant design, made it a popular choice among racing enthusiasts and collectors. The 212 Export is a significant model in Ferrari’s history, representing the brand’s early efforts to build cars that could excel in both road and race environments.', 'images/ferrari/212_export.jpg'),
(105, '1951 Ferrari 212 Inter', '$13,000,000 AUD', 'The Ferrari 212 Inter was a luxurious grand tourer designed for discerning customers. It was available with a variety of custom coachwork options and was known for its refined performance and elegance.', '8.5s', 'V12', 'Coupe', '1.1 tonnes', 'Steel', '2.6L', '165hp', 'The Ferrari 212 Inter, introduced in 1951, was a luxurious grand tourer designed for customers who wanted a high-performance car with elegant styling and refined comfort. The 212 Inter was powered by a 2.6-liter V12 engine that produced 165 horsepower, providing a smooth and capable driving experience. The car was available with custom coachwork from some of Italy’s most prestigious carrozzerias, including Ghia, Touring, and Vignale, making each 212 Inter unique. The 212 Inter’s elegant design and luxurious interior made it a favorite among wealthy enthusiasts who valued both performance and style. The car was successful in both road use and competition, further establishing Ferrari’s reputation as a builder of high-performance, luxurious grand tourers. The 212 Inter played a crucial role in Ferrari’s early success and helped to define the brand’s identity in the years to come.', 'images/ferrari/212_inter.jpg'),
(106, '1951 Ferrari 342 America', '$20,000,000 AUD', 'The Ferrari 342 America was a luxurious grand touring car designed for the American market. It featured a powerful V12 engine and was known for its exclusivity and bespoke coachwork.', '9s', 'V12', 'Coupe', '1.3 tonnes', 'Steel and Aluminum', '4.1L', '200hp', 'The Ferrari 342 America, introduced in 1951, was designed as an exclusive grand touring car aimed at the American market. The car was powered by a 4.1-liter V12 engine that produced 200 horsepower, providing smooth and powerful performance. The 342 America was available with custom coachwork from some of Italy’s leading carrozzerias, including Pininfarina, Ghia, and Vignale, which allowed customers to tailor the car’s design to their personal tastes. The car’s combination of power, luxury, and exclusivity made it highly desirable among wealthy buyers in the United States. The 342 America was produced in very limited numbers, adding to its exclusivity and appeal among collectors. The model is significant for its role in establishing Ferrari’s presence in the American market and for its contribution to the brand’s reputation as a builder of high-performance, luxurious grand tourers.', 'images/ferrari/342_america.jpg'),
(107, '1952 Ferrari 225 S', '$22,000,000 AUD', 'The Ferrari 225 S was a race car designed for privateers. It featured a powerful V12 engine and lightweight construction, making it a competitive car in events like the Mille Miglia and the Targa Florio.', '7.5s', 'V12', 'Coupe', '0.85 tonnes', 'Aluminum', '2.7L', '210hp', 'The Ferrari 225 S, introduced in 1952, was a competition car designed for privateer racers who wanted a car that could compete in endurance events like the Mille Miglia and the Targa Florio. The 225 S was powered by a 2.7-liter V12 engine that produced 210 horsepower, making it one of the most powerful race cars of its time. The car was designed with lightweight aluminum bodywork, which helped to improve its performance and handling. The 225 S was highly successful in racing, achieving numerous victories in events such as the Mille Miglia and the Targa Florio. The car’s combination of power, agility, and reliability made it a favorite among privateer racers and a key model in Ferrari’s racing history. The 225 S is also significant for its role in establishing Ferrari’s reputation as a builder of competitive race cars that could be driven by non-professional drivers.', 'images/ferrari/225_s.jpg'),
(108, '1952 Ferrari 250 S', '$24,000,000 AUD', 'The Ferrari 250 S was a prototype sports car that laid the groundwork for the legendary Ferrari 250 series. It featured a powerful V12 engine and was designed for endurance racing.', '7.2s', 'V12', 'Coupe', '0.88 tonnes', 'Aluminum', '2.96L', '230hp', 'The Ferrari 250 S, introduced in 1952, was a pivotal model in Ferrari’s history, serving as the prototype for the legendary 250 series that would follow. Powered by a 2.96-liter V12 engine producing 230 horsepower, the 250 S was designed for endurance racing, showcasing Ferrari’s engineering prowess and racing ambitions. The car featured lightweight aluminum bodywork, which contributed to its competitive performance on the track. The 250 S made its debut at the Mille Miglia in 1952, where it demonstrated its potential by finishing second overall, an impressive feat for a new car. This model’s success laid the foundation for the development of the 250 GT and 250 GTO, which would go on to become some of the most iconic and successful Ferraris of all time. The 250 S is remembered not only for its racing pedigree but also for its role in shaping the future of Ferrari’s V12-powered sports cars.', 'images/ferrari/250_s.jpg'),
(109, '1952 Ferrari 340 Mexico', '$26,000,000 AUD', 'The Ferrari 340 Mexico was a special edition built for the Carrera Panamericana. It featured a powerful V12 engine and was designed for high-speed endurance racing across Mexico.', '7.0s', 'V12', 'Coupe', '1.05 tonnes', 'Aluminum', '4.1L', '280hp', 'The Ferrari 340 Mexico, introduced in 1952, was a special edition sports car built specifically for the Carrera Panamericana, a grueling endurance race held in Mexico. The 340 Mexico was powered by a 4.1-liter V12 engine that produced 280 horsepower, making it one of the most powerful Ferraris of its time. The car’s design focused on high-speed stability and durability, with lightweight aluminum bodywork and a chassis optimized for the demanding conditions of the Mexican roads. The 340 Mexico was successful in the Carrera Panamericana, where it finished third overall, cementing Ferrari’s reputation as a builder of high-performance endurance racers. The model is significant for its role in Ferrari’s early racing history and for its contribution to the development of the 340 America series, which shared many of its design features. Today, the 340 Mexico is a rare and highly sought-after collector’s car, valued for its racing pedigree and historical significance.', 'images/ferrari/340_mexico.jpg'),
(110, '1953 Ferrari 250 Europa', '$28,000,000 AUD', 'The Ferrari 250 Europa was a luxurious grand tourer designed for long-distance travel. It was one of the first Ferraris to feature a V12 engine in the 250 series, setting the stage for future models.', '8.0s', 'V12', 'Coupe', '1.2 tonnes', 'Steel and Aluminum', '3.0L', '220hp', 'The Ferrari 250 Europa, introduced in 1953, was a groundbreaking model in Ferrari’s history, as it was one of the first Ferraris to feature the legendary 3.0-liter V12 engine that would become a hallmark of the 250 series. The 250 Europa was designed as a luxurious grand tourer, capable of covering long distances in comfort and style. The car was available with custom coachwork from some of Italy’s most prestigious carrozzerias, including Pininfarina and Vignale, which allowed customers to tailor the car’s design to their personal tastes. The 250 Europa’s combination of performance and luxury made it a favorite among wealthy enthusiasts, and its success helped to establish Ferrari’s reputation as a builder of high-performance grand tourers. The 250 Europa is also significant for its role in the development of the 250 series, which would go on to include some of Ferrari’s most iconic models, such as the 250 GT and the 250 GTO.', 'images/ferrari/250_europa.jpg'),
(111, '1953 Ferrari 250 MM', '$25,000,000 AUD', 'The Ferrari 250 MM, named after the Mille Miglia, was designed for endurance racing. It was the successor to the 250 S and featured improved aerodynamics and a more powerful V12 engine.', '7.4s', 'V12', 'Coupe', '0.98 tonnes', 'Aluminum', '3.0L', '240hp', 'The Ferrari 250 MM, introduced in 1953, was named after the Mille Miglia, one of the most famous endurance races in the world. The 250 MM was designed as a successor to the 250 S, with improvements in aerodynamics, handling, and power. The car was powered by a 3.0-liter V12 engine that produced 240 horsepower, providing a significant boost in performance over its predecessor. The 250 MM featured lightweight aluminum bodywork and a streamlined design that helped to improve its speed and agility on the track. The car was successful in various racing events, including the Mille Miglia, where it demonstrated Ferrari’s growing competitiveness in endurance racing. The 250 MM is significant for its role in the development of the 250 series and for its contribution to Ferrari’s early racing success. Today, the 250 MM is highly valued by collectors for its historical importance and its racing pedigree.', 'images/ferrari/250_mm.jpg'),
(112, '1953 Ferrari 340', '$23,000,000 AUD', 'The Ferrari 340 was a high-performance sports car designed for endurance racing. It featured a powerful V12 engine and was used in events such as the 24 Hours of Le Mans and the Mille Miglia.', '7.8s', 'V12', 'Coupe', '1.1 tonnes', 'Aluminum', '4.1L', '280hp', 'The Ferrari 340, introduced in 1953, was a high-performance sports car designed for endurance racing. Powered by a 4.1-liter V12 engine producing 280 horsepower, the 340 was one of the most powerful cars of its time. The car was designed with lightweight aluminum bodywork and a chassis optimized for high-speed stability, making it well-suited for long-distance races such as the 24 Hours of Le Mans and the Mille Miglia. The 340 was highly successful in competition, achieving numerous victories in both Europe and North America. The model is significant for its role in Ferrari’s early racing history and for its contribution to the development of the 340 America series, which shared many of its design features. Today, the Ferrari 340 is a rare and highly sought-after collector’s car, valued for its racing pedigree and historical significance.', 'images/ferrari/340.jpg'),
(113, '1953 Ferrari 375 America', '$30,000,000 AUD', 'The Ferrari 375 America was a luxurious grand tourer designed for the American market. It featured a large V12 engine and was known for its exclusivity and bespoke coachwork.', '7.0s', 'V12', 'Coupe', '1.3 tonnes', 'Steel and Aluminum', '4.5L', '300hp', 'The Ferrari 375 America, introduced in 1953, was designed as an exclusive grand touring car aimed at the American market. The car was powered by a 4.5-liter V12 engine that produced 300 horsepower, making it one of the most powerful road cars of its time. The 375 America was available with custom coachwork from some of Italy’s leading carrozzerias, including Pininfarina and Ghia, which allowed customers to tailor the car’s design to their personal tastes. The car’s combination of power, luxury, and exclusivity made it highly desirable among wealthy buyers in the United States. The 375 America was produced in very limited numbers, adding to its exclusivity and appeal among collectors. The model is significant for its role in establishing Ferrari’s presence in the American market and for its contribution to the brand’s reputation as a builder of high-performance, luxurious grand tourers.', 'images/ferrari/375_america.jpg'),
(114, '1953 Ferrari 375 MM', '$29,000,000 AUD', 'The Ferrari 375 MM was a race car designed for endurance racing. It featured a powerful V12 engine and was successful in events such as the 24 Hours of Le Mans and the Carrera Panamericana.', '6.8s', 'V12 ', 'Coupe', '1.1 tonnes', 'Aluminum', '4.5L', '340hp', 'The Ferrari 375 MM, introduced in 1953, was a race car designed for endurance racing. The “MM” stands for Mille Miglia, one of the most famous endurance races in the world, where the 375 MM achieved significant success. The car was powered by a 4.5-liter V12 engine that produced 340 horsepower, making it one of the most powerful Ferraris of its time. The 375 MM featured lightweight aluminum bodywork and a chassis designed for high-speed stability, making it well-suited for long-distance races such as the 24 Hours of Le Mans and the Carrera Panamericana. The car was highly successful in competition, achieving numerous victories and helping to establish Ferrari’s reputation as a builder of high-performance race cars. The 375 MM is significant for its role in Ferrari’s early racing history and for its contribution to the development of the 375 America series, which shared many of its design features. Today, the 375 MM is highly valued by collectors for its racing pedigree and historical significance.', 'images/ferrari/375_mm.jpg'),
(115, '1953 Ferrari 500 Modinal', '$22,000,000 AUD', 'The 1953 500 Modinal is a classic Ferrari model, known for its performance and design. It features a powerful engine and a sleek build, making it a collector’s favorite.', '7.5s', 'Inline-4', 'Coupe', '0.85 tonnes', 'Aluminum', '2.0L', '170hp', 'The 1953 500 Modinal was introduced during a time when Ferrari was establishing its reputation in motorsport. This model played a significant role in Ferrari’s early successes, particularly in endurance racing. It was powered by an inline-4 engine, delivering impressive performance for its time. The 500 Modinal was not just about speed; it also featured advanced engineering and a lightweight aluminum body, which contributed to its agility and handling. The car’s design was both functional and aesthetically pleasing, with a focus on aerodynamics and driver experience. Over the years, the 500 Modinal has become a cherished piece of automotive history, symbolizing Ferrari’s commitment to excellence and innovation in the early 1950s. Its legacy continues to inspire car enthusiasts and collectors around the world.', 'images/ferrari/500_modinal.jpg'),
(116, '1953 Ferrari 625 TF', '$7,700,000 AUD', 'The 1953 625 TF is a notable model in Ferrari’s history, known for its competitive edge in racing and its distinctive design. It remains a rare and valued car among collectors.', '6.8s', 'Inline-4', 'Spider', '0.9 tonnes', 'Aluminum', '2.5L', '220hp', 'The 1953 625 TF marked Ferrari’s continued push into competitive racing, especially in Formula Two. It was powered by a larger 2.5L engine compared to its predecessors, which gave it a competitive edge in terms of power and performance. The 625 TF was built with a lightweight aluminum body and featured advanced engineering techniques that were ahead of its time. This model achieved considerable success in various racing events, further cementing Ferrari’s status as a dominant force in motorsports. The design of the 625 TF was both functional and elegant, with an open-top spider body that emphasized its racing pedigree. Today, the 625 TF is considered a rare gem, highly sought after by collectors and car enthusiasts for its historical significance and racing heritage.', 'images/ferrari/625_tf.jpg');
INSERT INTO `cars` (`id`, `name`, `price`, `description`, `speed`, `engine_type`, `build`, `weight`, `material`, `engine_l`, `hp`, `history`, `image_url`) VALUES
(117, '1953 Ferrari 735 S', '$7,000,000 AUD', 'The 1953 735 S is celebrated for its robust performance and iconic design, making it a standout model from Ferrari’s early racing days. It remains a treasured car among vintage collectors.', '7.0s', 'Inline-6', 'Spider', '0.92 tonnes', 'Aluminum', '2.9L', '250hp', 'The 1953 735 S was one of Ferrari’s key models during the early 1950s, built primarily for racing. It featured an inline-6 engine, which was a departure from the smaller engines used in previous models. This provided the 735 S with significant power and speed, making it a formidable competitor on the track. The car was designed with a lightweight aluminum body, contributing to its agility and performance. The 735 S achieved notable success in various racing events, helping to establish Ferrari’s reputation in motorsport. Its design combined functionality with aesthetic appeal, characterized by sleek lines and an open-top spider body. Over the years, the 735 S has become a symbol of Ferrari’s engineering prowess and racing heritage. It remains a highly sought-after model for collectors and enthusiasts who appreciate its historical significance and performance capabilities.', 'images/ferrari/735_s.jpg'),
(118, '1954 Ferrari 250 GT Coupe', '$1,100,000 AUD', 'The 1954 250 GT Coupe is a classic Ferrari model, known for its elegance and performance. It is a favorite among collectors and car enthusiasts for its historical significance.', '6.5s', 'V12', 'Coupe', '1.1 tonnes', 'Steel', '3.0L', '240hp', 'The 1954 250 GT Coupe was a significant model in Ferrari’s lineup, representing the brand’s move towards more luxurious and road-oriented cars. It was powered by a 3.0L V12 engine, delivering impressive performance and a smooth driving experience. The 250 GT Coupe featured a steel body, which provided durability and a solid build. Its design was elegant and sophisticated, with a focus on both aesthetics and functionality. The car was well-received by both critics and customers, helping to establish Ferrari as a manufacturer of high-performance luxury cars. Over the years, the 250 GT Coupe has become a highly collectible model, valued for its design, performance, and historical importance. It remains a symbol of Ferrari’s commitment to excellence and innovation in automotive engineering.', 'images/ferrari/250_gt_coupe.jpg'),
(119, '1954 Ferrari 250 Monza', '$2,565,861 AUD', 'The 1954 250 Monza is renowned for its racing success and distinctive design. It is a prized model among collectors and car enthusiasts, representing Ferrari’s rich motorsport heritage.', '6.2s', 'V12', 'Spider', '0.98 tonnes', 'Aluminum', '3.0L', '260hp', 'The 1954 250 Monza was designed for racing, combining Ferrari’s engineering prowess with a focus on performance and speed. It featured a 3.0L V12 engine, which provided significant power and performance on the track. The car’s lightweight aluminum body contributed to its agility and handling, making it a formidable competitor in various racing events. The 250 Monza achieved considerable success in motorsport, helping to solidify Ferrari’s reputation as a leading manufacturer of racing cars. Its design was both functional and aesthetically pleasing, with an open-top spider body that emphasized its racing pedigree. Today, the 250 Monza is considered a rare and valuable model, highly sought after by collectors and car enthusiasts for its historical significance and performance capabilities. It remains a symbol of Ferrari’s commitment to innovation and excellence in the world of motorsport.', 'images/ferrari/250_monza.jpg'),
(120, '1954 Ferrari 375 Plus', '$18,000,000 AUD', 'The 1954 375 Plus is a significant model in Ferrari’s history, known for its powerful engine and racing success. It is a cherished car among collectors for its performance and design.', '5.8s', 'V12', 'Spider', '1.05 tonnes', 'Aluminum', '4.9L', '330hp', 'The 1954 375 Plus was one of Ferrari’s most powerful and successful racing cars of its time. It was powered by a 4.9L V12 engine, which provided immense power and performance on the track. The car’s lightweight aluminum body contributed to its agility and speed, making it a dominant force in various racing events. The 375 Plus achieved notable success in endurance races, including the prestigious 24 Hours of Le Mans. Its design was both functional and aesthetically appealing, characterized by sleek lines and an open-top spider body. Over the years, the 375 Plus has become a highly collectible model, valued for its historical significance and racing heritage. It remains a symbol of Ferrari’s engineering excellence and commitment to motorsport.', 'images/ferrari/375_plus.jpg'),
(121, '1954 Ferrari 750 Monza', '$4,566,950 AUD', 'The 1954 750 Monza is celebrated for its performance and design, making it a standout model from Ferrari’s early racing days. It remains a treasured car among vintage collectors.', '6.0s', 'Inline-4', 'Spider', '0.95 tonnes', 'Aluminum', '3.0L', '260hp', 'The 1954 750 Monza was designed for racing, featuring a powerful inline-4 engine that provided significant performance on the track. The car’s lightweight aluminum body contributed to its agility and handling, making it a formidable competitor in various racing events. The 750 Monza achieved considerable success in motorsport, helping to establish Ferrari’s reputation as a leading manufacturer of racing cars. Its design was both functional and aesthetically pleasing, with an open-top spider body that emphasized its racing pedigree. Over the years, the 750 Monza has become a symbol of Ferrari’s engineering prowess and racing heritage. It remains a highly sought-after model for collectors and enthusiasts who appreciate its historical significance and performance capabilities.', 'images/ferrari/750_monza.jpg'),
(122, '1955 Ferrari 376 S', '$8,750,000 AUD', 'The 1955 376 S is a notable model in Ferrari’s history, known for its competitive edge in racing and its distinctive design. It remains a rare and valued car among collectors.', '5.9s', 'Inline-6', 'Spider', '1.0 tonnes', 'Aluminum', '3.8L', '280hp', 'The 1955 376 S was one of Ferrari’s key models during the mid-1950s, built primarily for racing. It featured an inline-6 engine, which provided significant power and speed, making it a formidable competitor on the track. The car was designed with a lightweight aluminum body, contributing to its agility and performance. The 376 S achieved notable success in various racing events, helping to establish Ferrari’s reputation in motorsport. Its design combined functionality with aesthetic appeal, characterized by sleek lines and an open-top spider body. Over the years, the 376 S has become a symbol of Ferrari’s engineering prowess and racing heritage. It remains a highly sought-after model for collectors and enthusiasts who appreciate its historical significance and performance capabilities.', 'images/ferrari/376_s.jpg'),
(123, '1955 Ferrari 735 LM', '$5,720,000 AUD', 'The 1955 735 LM is a celebrated model in Ferrari’s history, known for its robust performance and iconic design. It remains a cherished car among vintage collectors.', '5.7s', 'Inline-6', 'Spider', '1.02 tonnes', 'Aluminum', '4.4L', '300hp', 'The 1955 735 LM was designed for endurance racing, featuring a powerful inline-6 engine that provided significant performance on the track. The car’s lightweight aluminum body contributed to its agility and handling, making it a formidable competitor in various racing events. The 735 LM achieved considerable success in motorsport, helping to establish Ferrari’s reputation as a leading manufacturer of racing cars. Its design was both functional and aesthetically appealing, with an open-top spider body that emphasized its racing pedigree. Over the years, the 735 LM has become a highly collectible model, valued for its historical significance and racing heritage. It remains a symbol of Ferrari’s engineering excellence and commitment to motorsport.', 'images/ferrari/735_lm.jpg'),
(124, '1955 Ferrari 857 S', '$6,270,000 AUD', 'The 1955 857 S is renowned for its racing success and distinctive design. It is a prized model among collectors and car enthusiasts, representing Ferrari’s rich motorsport heritage.', '5.5s', 'Inline-4', 'Spider', '0.97 tonnes', 'Aluminum', '3.4L', '275hp', 'The 1955 857 S was designed for racing, featuring a powerful inline-4 engine that provided significant performance on the track. The car’s lightweight aluminum body contributed to its agility and handling, making it a formidable competitor in various racing events. The 857 S achieved considerable success in motorsport, helping to solidify Ferrari’s reputation as a leading manufacturer of racing cars. Its design was both functional and aesthetically pleasing, with an open-top spider body that emphasized its racing pedigree. Today, the 857 S is considered a rare and valuable model, highly sought after by collectors and car enthusiasts for its historical significance and performance capabilities. It remains a symbol of Ferrari’s commitment to innovation and excellence in the world of motorsport.', 'images/ferrari/857_s.jpg'),
(125, '1956 Ferrari 250 GT Berlinetta', '$8,630,850 AUD', 'The 1956 250 GT Berlinetta is a classic Ferrari model, known for its elegance and performance. It is a favorite among collectors and car enthusiasts for its historical significance.', '6.0s', 'V12', 'Coupe', '1.15 tonnes', 'Steel', '3.0L', '240hp', 'The 1956 250 GT Berlinetta was a significant model in Ferrari’s lineup, representing the brand’s move towards more luxurious and road-oriented cars. It was powered by a 3.0L V12 engine, delivering impressive performance and a smooth driving experience. The 250 GT Berlinetta featured a steel body, which provided durability and a solid build. Its design was elegant and sophisticated, with a focus on both aesthetics and functionality. The car was well-received by both critics and customers, helping to establish Ferrari as a manufacturer of high-performance luxury cars. Over the years, the 250 GT Berlinetta has become a highly collectible model, valued for its design, performance, and historical importance. It remains a symbol of Ferrari’s commitment to excellence and innovation in automotive engineering.', 'images/ferrari/250_gt_berlinetta.jpg'),
(126, '1956 Ferrari 290 MM', '$33,171,160 AUD', 'The 1956 290 MM is a significant model in Ferrari’s history, known for its powerful engine and racing success. It is a cherished car among collectors for its performance and design.', '5.3s', 'V12', 'Spider', '1.02 tonnes', 'Aluminum', '3.5L', '320hp', 'The 1956 290 MM was one of Ferrari’s most powerful and successful racing cars of its time. It was powered by a 3.5L V12 engine, which provided immense power and performance on the track. The car’s lightweight aluminum body contributed to its agility and speed, making it a dominant force in various racing events. The 290 MM achieved notable success in endurance races, including the prestigious Mille Miglia. Its design was both functional and aesthetically appealing, characterized by sleek lines and an open-top spider body. Over the years, the 290 MM has become a highly collectible model, valued for its historical significance and racing heritage. It remains a symbol of Ferrari’s engineering excellence and commitment to motorsport.', 'images/ferrari/290_mm.jpg'),
(127, '1956 Ferrari 410 S', '$33,200,000 AUD', 'The 1956 410 S is celebrated for its robust performance and iconic design, making it a standout model from Ferrari’s early racing days. It remains a treasured car among vintage collectors.', '5.1s', 'V12', 'Spider', '1.08 tonnes', 'Aluminum', '4.9L', '340hp', 'The 1956 410 S was designed for racing, featuring a powerful 4.9L V12 engine that provided significant performance on the track. The car’s lightweight aluminum body contributed to its agility and handling, making it a formidable competitor in various racing events. The 410 S achieved considerable success in motorsport, helping to establish Ferrari’s reputation as a leading manufacturer of racing cars. Its design was both functional and aesthetically appealing, with an open-top spider body that emphasized its racing pedigree. Over the years, the 410 S has become a highly collectible model, valued for its historical significance and racing heritage. It remains a symbol of Ferrari’s engineering excellence and commitment to motorsport.', 'images/ferrari/410_s.jpg'),
(128, '1956 Ferrari 410 Superamerica', '$4,218,956 AUD', 'The 1956 410 Superamerica is a notable model in Ferrari’s history, known for its luxury and performance. It remains a rare and valued car among collectors.', '5.6s', 'V12', 'Coupe', '1.22 tonnes', 'Steel', '4.9L', '340hp', 'The 1956 410 Superamerica was one of Ferrari’s most luxurious and powerful road cars of its time. It was powered by a 4.9L V12 engine, delivering impressive performance and a smooth driving experience. The car’s design was both elegant and sophisticated, with a focus on luxury and comfort. The 410 Superamerica featured a steel body, which provided durability and a solid build. It was well-received by both critics and customers, helping to establish Ferrari as a manufacturer of high-performance luxury cars. Over the years, the 410 Superamerica has become a highly collectible model, valued for its design, performance, and historical importance. It remains a symbol of Ferrari’s commitment to excellence and innovation in automotive engineering.', 'images/ferrari/410_superamerica.jpg'),
(129, '1956 Ferrari 500 TR', '$1,085,801 AUD', 'The 1956 500 TR is celebrated for its performance and design, making it a standout model from Ferrari’s early racing days. It remains a treasured car among vintage collectors.', '5.4s', 'Inline-4', 'Spider', '0.92 tonnes', 'Aluminum', '2.0L', '190hp', 'The 1956 500 TR was designed for racing, featuring a powerful inline-4 engine that provided significant performance on the track. The car’s lightweight aluminum body contributed to its agility and handling, making it a formidable competitor in various racing events. The 500 TR achieved considerable success in motorsport, helping to establish Ferrari’s reputation as a leading manufacturer of racing cars. Its design was both functional and aesthetically pleasing, with an open-top spider body that emphasized its racing pedigree. Over the years, the 500 TR has become a symbol of Ferrari’s engineering prowess and racing heritage. It remains a highly sought-after model for collectors and enthusiasts who appreciate its historical significance and performance capabilities.', 'images/ferrari/500_tr.jpg'),
(130, '1956 Ferrari 625 LM', 'Unknown', 'The 1956 625 LM is a significant model in Ferrari’s history, known for its competitive edge in racing and its distinctive design. It remains a rare and valued car among collectors.', '5.2s', 'Inline-4', 'Spider', '0.96 tonnes', 'Aluminum', '2.5L', '225hp', 'The 1956 625 LM was designed for endurance racing, featuring a powerful inline-4 engine that provided significant performance on the track. The car’s lightweight aluminum body contributed to its agility and handling, making it a formidable competitor in various racing events. The 625 LM achieved considerable success in motorsport, helping to establish Ferrari’s reputation as a leading manufacturer of racing cars. Its design was both functional and aesthetically pleasing, with an open-top spider body that emphasized its racing pedigree. Over the years, the 625 LM has become a highly collectible model, valued for its historical significance and racing heritage. It remains a symbol of Ferrari’s engineering excellence and commitment to motorsport.', 'images/ferrari/625_lm.jpg'),
(131, '1956 Ferrari 860 Monza', '$3,104,784 AUD', 'The 1956 860 Monza is renowned for its racing success and distinctive design. It is a prized model among collectors and car enthusiasts, representing Ferrari’s rich motorsport heritage.', '5.0s', 'Inline-4', 'Spider', '0.98 tonnes', 'Aluminum', '3.4L', '280hp', 'The 1956 860 Monza was designed for racing, featuring a powerful inline-4 engine that provided significant performance on the track. The car’s lightweight aluminum body contributed to its agility and handling, making it a formidable competitor in various racing events. The 860 Monza achieved considerable success in motorsport, helping to solidify Ferrari’s reputation as a leading manufacturer of racing cars. Its design was both functional and aesthetically pleasing, with an open-top spider body that emphasized its racing pedigree. Today, the 860 Monza is considered a rare and valuable model, highly sought after by collectors and car enthusiasts for its historical significance and performance capabilities. It remains a symbol of Ferrari’s commitment to innovation and excellence in the world of motorsport.', 'images/ferrari/860_monza.jpg'),
(132, '1957 Ferrari 250 California', '$30,000,000 AUD', 'The 1957 250 California is a classic Ferrari model, known for its elegance and performance. It is a favorite among collectors and car enthusiasts for its historical significance.', '5.8s', 'V12', 'Spider', '1.08 tonnes', 'Steel', '3.0L', '240hp', 'The 1957 250 California was a significant model in Ferrari’s lineup, representing the brand’s move towards more luxurious and road-oriented cars. It was powered by a 3.0L V12 engine, delivering impressive performance and a smooth driving experience. The 250 California featured a steel body, which provided durability and a solid build. Its design was elegant and sophisticated, with a focus on both aesthetics and functionality. The car was well-received by both critics and customers, helping to establish Ferrari as a manufacturer of high-performance luxury cars. Over the years, the 250 California has become a highly collectible model, valued for its design, performance, and historical importance. It remains a symbol of Ferrari’s commitment to excellence and innovation in automotive engineering.', 'images/ferrari/250_california.jpg'),
(133, '1957 Ferrari 250 GT Cabriolet', '$15,000,000 AUD', 'The 1957 250 GT Cabriolet is a notable model in Ferrari’s history, known for its luxury and performance. It remains a rare and valued car among collectors.', '6.2s', 'V12', 'Cabriolet', '1.1 tonnes', 'Steel', '3.0L', '240hp', 'The 1957 250 GT Cabriolet was one of Ferrari’s most luxurious and powerful road cars of its time. It was powered by a 3.0L V12 engine, delivering impressive performance and a smooth driving experience. The car’s design was both elegant and sophisticated, with a focus on luxury and comfort. The 250 GT Cabriolet featured a steel body, which provided durability and a solid build. It was well-received by both critics and customers, helping to establish Ferrari as a manufacturer of high-performance luxury cars. Over the years, the 250 GT Cabriolet has become a highly collectible model, valued for its design, performance, and historical importance. It remains a symbol of Ferrari’s commitment to excellence and innovation in automotive engineering.', 'images/ferrari/250_gt_cabriolet.jpg'),
(134, '1957 Ferrari 250 Testa Rossa', '$18,000,000 AUD', 'The 1957 250 Testa Rossa is celebrated for its performance and design, making it a standout model from Ferrari’s early racing days. It remains a treasured car among vintage collectors.', '5.5s', 'V12', 'Spider', '1.0 tonnes', 'Aluminum', '3.0L', '300hp', 'The 1957 250 Testa Rossa was designed for racing, featuring a powerful 3.0L V12 engine that provided significant performance on the track. The car’s lightweight aluminum body contributed to its agility and handling, making it a formidable competitor in various racing events. The 250 Testa Rossa achieved considerable success in motorsport, helping to establish Ferrari’s reputation as a leading manufacturer of racing cars. Its design was both functional and aesthetically pleasing, with an open-top spider body that emphasized its racing pedigree. Over the years, the 250 Testa Rossa has become a symbol of Ferrari’s engineering prowess and racing heritage. It remains a highly sought-after model for collectors and enthusiasts who appreciate its historical significance and performance capabilities.', 'images/ferrari/250_testa_rossa.jpg'),
(135, '1957 Ferrari 290 S', '$33,231,880 AUD', 'The 1957 290 S is a significant model in Ferrari’s history, known for its powerful engine and racing success. It is a cherished car among collectors for its performance and design.', '5.1s', 'V12', 'Spider', '0.98 tonnes', 'Aluminum', '3.5L', '320hp', 'The 1957 290 S was one of Ferrari’s most powerful and successful racing cars of its time. It was powered by a 3.5L V12 engine, which provided immense power and performance on the track. The car’s lightweight aluminum body contributed to its agility and speed, making it a dominant force in various racing events. The 290 S achieved notable success in endurance races, including the prestigious Mille Miglia. Its design was both functional and aesthetically appealing, characterized by sleek lines and an open-top spider body. Over the years, the 290 S has become a highly collectible model, valued for its historical significance and racing heritage. It remains a symbol of Ferrari’s engineering excellence and commitment to motorsport.', 'images/ferrari/290_s.jpg'),
(136, '1957 Ferrari 315 S', '$53,424,693 AUD', 'The 1957 315 S is renowned for its racing success and distinctive design. It is a prized model among collectors and car enthusiasts, representing Ferrari’s rich motorsport heritage.', '4.9s', 'V12', 'Spider', '1.0 tonnes', 'Aluminum', '3.8L', '360hp', 'The 1957 315 S was designed for racing, featuring a powerful 3.8L V12 engine that provided significant performance on the track. The car’s lightweight aluminum body contributed to its agility and handling, making it a formidable competitor in various racing events. The 315 S achieved considerable success in motorsport, helping to solidify Ferrari’s reputation as a leading manufacturer of racing cars. Its design was both functional and aesthetically pleasing, with an open-top spider body that emphasized its racing pedigree. Today, the 315 S is considered a rare and valuable model, highly sought after by collectors and car enthusiasts for its historical significance and performance capabilities. It remains a symbol of Ferrari’s commitment to innovation and excellence in the world of motorsport.', 'images/ferrari/315_s.jpg'),
(137, '1957 Ferrari 315 S', '$53,302,689 AUD', 'The Ferrari 315 S was designed for endurance racing, featuring a powerful V12 engine. It was built to compete in events like the Mille Miglia.', '6.8s', 'V12', 'Roadster', '1.0 tonnes', 'Aluminum', '3.8L', '360hp', 'The Ferrari 315 S, introduced in 1957, played a crucial role in Ferrari’s racing success during the late 1950s.', 'images/ferrari/315_s.jpg'),
(138, '1957 Ferrari 335 S', '$53,302,876 AUD', 'The Ferrari 335 S is an iconic race car with a robust V12 engine. It achieved victories in several endurance races.', '6.5s', 'V12', 'Roadster', '0.98 tonnes', 'Aluminum', '4.0L', '390hp', 'The 335 S was an evolution of the 315 S and helped Ferrari secure its place at the top of the racing world in 1957.', 'images/ferrari/335_s.jpg'),
(139, '1957 Ferrari 500 TRC', '$6,545,351 AUD', 'The Ferrari 500 TRC was an evolution of the 500 TR, built to meet the latest racing regulations with a 2.0L four-cylinder engine.', '7.2s', 'Inline-4', 'Roadster', '0.85 tonnes', 'Steel and Aluminum', '2.0L', '190hp', 'The 500 TRC, with its improved aerodynamics and handling, was Ferrari’s last four-cylinder racing car.', 'images/ferrari/500_trc.jpg'),
(140, '1958 Ferrari 312 S', 'Unknown AUD', 'The Ferrari 312 S was built for high-speed endurance racing, featuring a V12 engine designed to deliver maximum performance.', '6.7s', 'V12', 'Roadster', '0.95 tonnes', 'Aluminum', '3.0L', '320hp', 'The 312 S was part of Ferrari’s lineup aimed at dominating the racing circuits in the late 1950s.', 'images/ferrari/312_s.jpg'),
(141, '1958 Ferrari 412 S', '$8,452,701 AUD', 'The Ferrari 412 S was a one-off racing prototype designed to compete in American races, powered by a massive V12 engine.', '6.2s', 'V12', 'Roadster', '1.1 tonnes', 'Aluminum', '4.0L', '450hp', 'The 412 S was known for its sheer power and performance, making it one of the most formidable race cars of its time.', 'images/ferrari/412_s.jpg'),
(142, '1958 Ferrari Dino 196 S', 'Unknown AUD', 'The Ferrari Dino 196 S was a lightweight sports prototype designed for agility and speed, featuring a V6 engine.', '7.1s', 'V6', 'Roadster', '0.78 tonnes', 'Aluminum', '2.0L', '195hp', 'The Dino 196 S was part of Ferrari’s efforts to create a smaller, more nimble racing car that could still compete at the highest levels.', 'images/ferrari/dino_196_s.jpg'),
(143, '1958 Ferrari Dino 296 S', 'Unknown AUD', 'The Ferrari Dino 296 S was an evolution of the Dino series, featuring a more powerful V6 engine and improved aerodynamics.', '6.9s', 'V6', 'Roadster', '0.82 tonnes', 'Aluminum', '2.9L', '240hp', 'The Dino 296 S represented Ferrari’s continued innovation in creating competitive mid-engine race cars.', 'images/ferrari/dino_296_s.jpg'),
(144, '1959 Ferrari 250 GT Berlinetta Passo Corto', 'Unknown', 'The Ferrari 250 GT Berlinetta Passo Corto, also known as the SWB (Short Wheelbase), was one of Ferrari’s most successful GT racers.', '6.2s', 'V12', 'Coupe', '1.0 tonnes', 'Steel and Aluminum', '3.0L', '280hp', 'The 250 GT SWB was known for its perfect blend of performance, handling, and style, making it a favorite among Ferrari enthusiasts.', 'images/ferrari/250_gt_berlinetta.jpg'),
(145, '1960 Ferrari 250 GT 2+2', '$3,153,764 AUD', 'The Ferrari 250 GT 2+2, also known as the GTE, was Ferrari’s first production four-seater, combining luxury with performance.', '7.5s', 'V12', 'Coupe', '1.2 tonnes', 'Steel', '3.0L', '240hp', 'The 250 GT 2+2 was Ferrari’s move towards more practical yet still powerful grand touring cars.', 'images/ferrari/250_gt_2plus2.jpg'),
(146, '1960 Ferrari 400 Superamerica', '$15,000,000 AUD', 'The Ferrari 400 Superamerica was an exclusive, luxurious grand tourer with a powerful V12 engine, built for the wealthiest clients.', '6.8s', 'V12', 'Coupe', '1.4 tonnes', 'Steel', '4.0L', '340hp', 'The 400 Superamerica represented the pinnacle of Ferrari luxury in the early 1960s.', 'images/ferrari/400_superamerica.jpg'),
(147, '1960 Ferrari Dino 246 S', '$1,998,384 AUD', 'The Ferrari Dino 246 S was a sports prototype racer with a V6 engine, continuing the Dino line’s success in racing.', '7.0s', 'V6', 'Roadster', '0.84 tonnes', 'Aluminum', '2.4L', '250hp', 'The 246 S was known for its agility and speed, making it a competitive car in sports car racing.', 'images/ferrari/dino_246_s.jpg'),
(148, '1961 Ferrari 246 SP', '$13,580,604 AUD', 'The Ferrari 246 SP was the first mid-engine car built by Ferrari, marking a significant shift in Ferrari’s design philosophy.', '6.5s', 'V6', 'Roadster', '0.82 tonnes', 'Aluminum', '2.4L', '270hp', 'The 246 SP’s success in races like the Targa Florio solidified Ferrari’s decision to pursue mid-engine designs.', 'images/ferrari/246_sp.jpg'),
(149, '1962 Ferrari 196 SP', '$13,580,600 AUD', 'The Ferrari 196 SP was a lightweight, nimble sports prototype, designed to excel in endurance races.', '7.0s', 'V6', 'Roadster', '0.80 tonnes', 'Aluminum', '2.0L', '210hp', 'The 196 SP was part of Ferrari’s effort to build smaller, more efficient race cars that could still dominate on the track.', 'images/ferrari/196_sp.jpg'),
(150, '1962 Ferrari 248 SP', '$11,624,572 AUD', 'The Ferrari 248 SP was an evolution of the 196 SP, with a slightly larger engine and improved performance.', '6.8s', 'V6', 'Roadster', '0.82 tonnes', 'Aluminum', '2.5L', '230hp', 'The 248 SP continued Ferrari’s success in mid-engine sports prototypes, offering greater speed and handling.', 'images/ferrari/248_sp.jpg'),
(151, '1962 Ferrari 250 Berlinetta Lusso', '$4,231,917 AUD', 'The Ferrari 250 Berlinetta Lusso was a luxurious version of the 250 series, blending performance with comfort.', '7.2s', 'V12', 'Coupe', '1.2 tonnes', 'Steel and Aluminum', '3.0L', '240hp', 'The Berlinetta Lusso was favored by wealthy drivers who desired both speed and refinement.', 'images/ferrari/250_berlinetta_lusso.jpg'),
(152, '1962 Ferrari 250 GTO', '$78,007,592 AUD', 'The Ferrari 250 GTO is one of the most iconic and sought-after cars in automotive history, built for racing and homologation purposes.', '6.1s', 'V12', 'Coupe', '1.0 tonnes', 'Aluminum', '3.0L', '300hp', 'The 250 GTO is legendary for its racing success and is one of the most valuable cars ever built.', 'images/ferrari/250_gto.jpg'),
(153, '1962 Ferrari 268 SP', '$11,624,572 AUD', 'The Ferrari 268 SP was a mid-engine sports prototype with a unique V8 engine, built for endurance racing.', '6.7s', 'V8', 'Roadster', '0.88 tonnes', 'Aluminum', '2.6L', '250hp', 'The 268 SP represented Ferrari’s experimentation with different engine configurations for racing.', 'images/ferrari/268_sp.jpg'),
(154, '1962 Ferrari 286 SP', 'Unknown', 'The Ferrari 286 SP was a further evolution of the SP series, featuring a more powerful V8 engine for improved performance.', '6.5s', 'V8', 'Roadster', '0.90 tonnes', 'Aluminum', '2.9L', '270hp', 'The 286 SP was designed to compete in the most demanding endurance races, showcasing Ferrari’s engineering prowess.', 'images/ferrari/286_sp.jpg'),
(155, '1962 Ferrari 330 LM', '$78,024,396 AUD', 'The Ferrari 330 LM, also known as the 330 LMB, was a race car built for long-distance events, featuring a powerful V12 engine.', '6.3s', 'V12', 'Coupe', '1.1 tonnes', 'Aluminum', '4.0L', '390hp', 'The 330 LM was part of Ferrari’s strategy to dominate endurance racing in the early 1960s.', 'images/ferrari/330_lm.jpg'),
(156, '1962 Ferrari 330 TR', '$8,903,277 AUD', 'The Ferrari 330 TR was a one-off race car built to compete in the 1962 24 Hours of Le Mans, featuring a 4.0L V12 engine.', '6.1s', 'V12', 'Roadster', '1.05 tonnes', 'Aluminum', '4.0L', '390hp', 'The 330 TR was the last front-engine car to win Le Mans, marking the end of an era for Ferrari.', 'images/ferrari/330_tr.jpg'),
(157, '1963 Ferrari 250 LM', '$24,140,000 AUD', 'The Ferrari 250 LM was a mid-engine sports car designed for endurance racing, continuing the legacy of the 250 series.', '6.2s', 'V12', 'Coupe', '1.0 tonnes', 'Aluminum', '3.3L', '320hp', 'The 250 LM was the first mid-engine Ferrari to win the 24 Hours of Le Mans.', 'images/ferrari/250_lm.jpg'),
(158, '1963 Ferrari 250 P', '$15,060,000 AUD', 'The Ferrari 250 P was a sports prototype designed for endurance racing, featuring a mid-engine layout and a powerful V12 engine.', '6.3s', 'V12', 'Roadster', '0.98 tonnes', 'Aluminum', '3.0L', '310hp', 'The 250 P was a successful race car, winning several prestigious events including the 24 Hours of Le Mans.', 'images/ferrari/250_p.jpg'),
(159, '1963 Ferrari 330 P', '$3,017,520 AUD', 'The Ferrari 330 P was a series of sports prototype racing cars, featuring a mid-engine design and a V12 engine.', '6.4s', 'V12', 'Roadster', '1.0 tonnes', 'Aluminum', '4.0L', '410hp', 'The 330 P was designed to compete in endurance races and was part of Ferrari’s legendary P series.', 'images/ferrari/330_p.jpg'),
(160, '1964 Ferrari 275 GTB', '$5,280,660 AUD', 'The Ferrari 275 GTB was a front-engine GT car known for its performance and beautiful design, featuring a V12 engine.', '6.5s', 'V12', 'Coupe', '1.2 tonnes', 'Steel', '3.3L', '280hp', 'The 275 GTB was one of Ferrari’s most celebrated road cars of the 1960s.', 'images/ferrari/275_gtb.jpg'),
(161, '1964 Ferrari 275 GTS', '$2,359,707 AUD', 'The Ferrari 275 GTS was the convertible version of the 275 GTB, offering open-top driving with Ferrari’s iconic V12 engine.', '6.7s', 'V12', 'Convertible', '1.2 tonnes', 'Steel', '3.3L', '260hp', 'The 275 GTS combined Ferrari performance with the pleasure of open-air motoring.', 'images/ferrari/275_gts.jpg'),
(162, '1964 Ferrari 275 P', '$67,890,436 AUD', 'The Ferrari 275 P was a sports prototype racer, designed for endurance racing with a mid-engine V12.', '6.3s', 'V12', 'Roadster', '0.98 tonnes', 'Aluminum', '3.3L', '320hp', 'The 275 P continued Ferrari’s success in endurance racing, securing wins in multiple major events.', 'images/ferrari/275_p.jpg'),
(163, '1964 Ferrari 330 GT 2+2', 'Unknown', 'The Ferrari 330 GT 2+2 was a luxurious grand tourer with seating for four, powered by a V12 engine.', '7.4s', 'V12', 'Coupe', '1.4 tonnes', 'Steel', '4.0L', '300hp', 'The 330 GT 2+2 was Ferrari’s response to the demand for a more practical yet powerful grand tourer.', 'images/ferrari/330_gt_2plus2.jpg'),
(164, '1964 Ferrari 500 Superfast', '$2,813,754 AUD', 'The Ferrari 500 Superfast was the pinnacle of Ferrari’s luxury offerings in the mid-1960s, featuring a 5.0L V12 engine.', '6.0s', 'V12', 'Coupe', '1.5 tonnes', 'Steel', '5.0L', '400hp', 'The 500 Superfast was designed for Ferrari’s wealthiest clients, offering unparalleled luxury and performance.', 'images/ferrari/500_superfast.jpg'),
(165, '1965 Ferrari 275 GTB Competizione', '$11,625,627 AUD', 'The Ferrari 275 GTB Competizione was a race-ready version of the 275 GTB, featuring a lightweight body and a more powerful V12 engine.', '6.0s', 'V12', 'Coupe', '1.1 tonnes', 'Aluminum', '3.3L', '300hp', 'The 275 GTB Competizione was built for endurance racing and was successful in events like the 24 Hours of Le Mans.', 'images/ferrari/275_gtb_competizione.jpg'),
(166, '1965 Ferrari 275 P2', 'Unknown', 'The Ferrari 275 P2 was a sports prototype designed for endurance racing, featuring a mid-engine V12 and advanced aerodynamics.', '6.2s', 'V12', 'Roadster', '0.95 tonnes', 'Aluminum', '3.3L', '320hp', 'The 275 P2 was part of Ferrari’s continued dominance in sports car racing during the mid-1960s.', 'images/ferrari/275_p2.jpg'),
(167, '1965 Ferrari 330 P2', 'Unknown', 'The Ferrari 330 P2 was an evolution of the P series, featuring a larger V12 engine and improved performance for endurance racing.', '6.1s', 'V12', 'Roadster', '1.0 tonnes', 'Aluminum', '4.0L', '410hp', 'The 330 P2 was a formidable competitor in endurance racing, continuing Ferrari’s legacy of success.', 'images/ferrari/330_p2.jpg'),
(168, '1965 Ferrari 365 P', 'Unknown', 'The Ferrari 365 P was a prototype sports car featuring a unique 3-seat configuration with a mid-engine V12.', '6.0s', 'V12', 'Coupe', '1.2 tonnes', 'Aluminum', '4.4L', '380hp', 'The 365 P was a revolutionary design by Ferrari, combining innovation with performance.', 'images/ferrari/365_p.jpg'),
(169, '1965 Ferrari Dino 166 P', 'Unknown', 'The Ferrari Dino 166 P was a lightweight sports prototype, featuring a V6 engine and designed for agility on the track.', '6.9s', 'V6', 'Roadster', '0.78 tonnes', 'Aluminum', '1.6L', '185hp', 'The 166 P was part of the Dino line, known for its excellent handling and performance.', 'images/ferrari/dino_166_p.jpg'),
(170, '1970 Ferrari 512 S', '$4,376,171 AUD', 'The Ferrari 512 S was a sports prototype racer built for endurance racing, featuring a powerful V12 engine and lightweight design.', '5.9s', 'V12', 'Roadster', '1.0 tonnes', 'Aluminum', '5.0L', '550hp', 'The 512 S competed in the World Sportscar Championship, known for its performance in endurance events.', 'images/ferrari/512_s.jpg'),
(171, '1971 Ferrari 312 P', '$8,643,815 AUD', 'The Ferrari 312 P was an endurance racing car with a 3.0L V12 engine, designed to compete in the World Sportscar Championship.', '6.1s', 'V12', 'Roadster', '0.95 tonnes', 'Aluminum', '3.0L', '420hp', 'The 312 P was part of Ferrari’s return to endurance racing, known for its speed and handling.', 'images/ferrari/312_p_1971.jpg'),
(172, '1971 Ferrari 365 GT4 BB', '$754,520 AUD', 'The Ferrari 365 GT4 BB was the first mid-engine road car by Ferrari, featuring a flat-12 engine and aggressive styling.', '6.5s', 'Flat-12', 'Coupe', '1.2 tonnes', 'Steel', '4.4L', '380hp', 'The 365 GT4 BB was a radical departure for Ferrari, marking the start of the Berlinetta Boxer series.', 'images/ferrari/365_gt4_bb.jpg'),
(173, '1971 Ferrari 365 GTB4 Competizione', '$3,392,615 AUD', 'The Ferrari 365 GTB4 Competizione was a race-prepped version of the Daytona, designed for endurance racing.', '5.9s', 'V12', 'Coupe', '1.1 tonnes', 'Aluminum', '4.4L', '450hp', 'The Competizione variant of the Daytona was highly successful in racing, including at Le Mans.', 'images/ferrari/365_gtb4_competizione.jpg'),
(174, '1971 Ferrari 365 GTC4', '$455,364 AUD', 'The Ferrari 365 GTC4 was a luxurious grand tourer with a front-engine V12, offering comfort and performance.', '6.8s', 'V12', 'Coupe', '1.4 tonnes', 'Steel', '4.4L', '340hp', 'The 365 GTC4 was designed for long-distance touring, known for its smooth ride and powerful engine.', 'images/ferrari/365_gtc4.jpg'),
(175, '1971 Ferrari 712 Can Am', '$2,563,309 AUD', 'The Ferrari 712 Can Am was a racing prototype designed for the Can-Am series, featuring a massive V12 engine.', '5.8s', 'V12', 'Roadster', '1.0 tonnes', 'Aluminum', '7.0L', '680hp', 'The 712 Can Am was one of Ferrari’s most powerful race cars, built for the highly competitive Can-Am series.', 'images/ferrari/712_can_am.jpg'),
(176, '1972 Ferrari 365 GT4 2+2', '$105,000 AUD', 'The Ferrari 365 GT4 2+2 was a luxurious grand tourer with seating for four, powered by a front-engine V12.', '7.0s', 'V12', 'Coupe', '1.5 tonnes', 'Steel', '4.4L', '340hp', 'The 365 GT4 2+2 was known for its combination of comfort and performance, making it a popular choice for long-distance driving.', 'images/ferrari/365_gt4_2plus2.jpg'),
(177, '1972 Ferrari Dino 246 GTS', '$1,052,718 AUD', 'The Ferrari Dino 246 GTS was the targa top version of the Dino 246 GT, offering open-air driving with a V6 engine.', '7.2s', 'V6', 'Targa', '1.1 tonnes', 'Aluminum', '2.4L', '195hp', 'The Dino 246 GTS is beloved for its balance of performance and design, making it one of Ferrari’s most iconic models.', 'images/ferrari/dino_246_gts.jpg'),
(178, '1973 Ferrari Dino 308 GT4', '$679,461 AUD', 'The Ferrari Dino 308 GT4 was a 2+2 mid-engine sports car, featuring a V8 engine and angular styling by Bertone.', '7.5s', 'V8', 'Coupe', '1.3 tonnes', 'Steel', '3.0L', '255hp', 'The 308 GT4 was the first Ferrari-badged car to feature a V8 engine, marking a new direction for the brand.', 'images/ferrari/dino_308_gt4.jpg'),
(179, '1975 Ferrari 308 GTB', '$123,000 AUD', 'The Ferrari 308 GTB was a mid-engine sports car with a V8 engine, known for its beautiful design and performance.', '6.8s', 'V8', 'Coupe', '1.2 tonnes', 'Steel', '3.0L', '255hp', 'The 308 GTB became one of Ferrari’s most successful models, beloved for its style and handling.', 'images/ferrari/308_gtb.jpg'),
(180, '1975 Ferrari Dino 208 GT4', '$62,906 AUD', 'The Ferrari Dino 208 GT4 was a smaller-engined version of the 308 GT4, designed to meet Italian tax regulations.', '8.0s', 'V8', 'Coupe', '1.3 tonnes', 'Steel', '2.0L', '170hp', 'The 208 GT4 was unique to the Italian market, offering Ferrari’s performance in a more affordable package.', 'images/ferrari/dino_208_gt4.jpg'),
(181, '1976 Ferrari 400 Automatic', '$54,858 AUD', 'The Ferrari 400 Automatic was a grand tourer with an automatic transmission, featuring a front-engine V12.', '7.5s', 'V12', 'Coupe', '1.6 tonnes', 'Steel', '4.8L', '335hp', 'The 400 Automatic was Ferrari’s first production car with an automatic gearbox, catering to luxury-oriented customers.', 'images/ferrari/400_automatic.jpg'),
(182, '1976 Ferrari 400 GT', '$77,872 AUD', 'The Ferrari 400 GT was a luxurious grand tourer with a V12 engine, offering a combination of performance and comfort.', '7.3s', 'V12', 'Coupe', '1.6 tonnes', 'Steel', '4.8L', '335hp', 'The 400 GT continued Ferrari’s tradition of high-performance grand touring cars, known for its power and refinement.', 'images/ferrari/400_gt.jpg'),
(183, '1976 Ferrari 512 BB', '$705,285 AUD', 'The Ferrari 512 BB was an evolution of the 365 GT4 BB, featuring a larger flat-12 engine and improved performance.', '6.0s', 'Flat-12', 'Coupe', '1.4 tonnes', 'Steel', '5.0L', '360hp', 'The 512 BB was known for its combination of power and handling, making it one of Ferrari’s most iconic models.', 'images/ferrari/512_bb.jpg'),
(184, '1977 Ferrari 308 GTS', '$226,105 AUD', 'The Ferrari 308 GTS was the targa top version of the 308 GTB, offering open-air driving with Ferrari’s mid-engine V8.', '6.9s', 'V8', 'Targa', '1.2 tonnes', 'Steel', '3.0L', '255hp', 'The 308 GTS became famous for its role in the TV series Magnum, P.I., cementing its status as a cultural icon.', 'images/ferrari/308_gts.jpg'),
(185, '1978 Ferrari 512 BB LM', '$367,494 AUD', 'The Ferrari 512 BB LM was a race-prepared version of the 512 BB, designed for endurance racing.', '5.7s', 'Flat-12', 'Coupe', '1.1 tonnes', 'Aluminum', '5.0L', '470hp', 'The 512 BB LM competed at Le Mans, showcasing Ferrari’s racing pedigree with its powerful flat-12 engine.', 'images/ferrari/512_bb_lm.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cars`
--
ALTER TABLE `cars`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cars`
--
ALTER TABLE `cars`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=186;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;